[package]
name = "dotprofilers"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "dp"
path = "src/bin/dp.rs"

[dependencies]
clap = { version = "4.5.37", features = ["derive", "env", "cargo"] }
log = "0.4.27"
env_logger = "0.11.8"