[package]
name = "dotprofiles-config"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true
lazy_static.workspace = true
dirs-next.workspace = true
toml.workspace = true
serde.workspace = true
anyhow.workspace = true
